Update notebook output
It's still panicking because of the FilterInterface logic @manghi added:

  panicked at 'failed to acquire notify rx lock: TryLockError(())', nwv2-python-wrapper/src/filter/mod.rs:221:18